language: R
cache:
  - packages
  - ccache
latex: false
sudo: required
os: linux
dist: trusty

r:
#  - release
  - oldrel

before_install:
#  Add GDAL, GEOS, proj, and units2 dependencies
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libgdal-dev libgeos-dev libproj-dev libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler libjq-dev libgdal1-dev proj-bin

r_binary_packages:
  - lwgeom
  - units
  - sp
  - rgdal
  - rgeos
  - sf
  - markdown
  - rmarkdown
  - httr
  - jsonlite
  - digest
  - dplyr
  - readr
  - stringi
  - tidyr
  - ggplot2
  - geojsonsf
  - rlang

